---
- name: Install httpd
  yum:
    name: httpd
    state: latest
  with_items:
    - httpd
- name: Restart HTTPD (Red Hat/Centos)
  service: name=httpd state=restarted
- name: send index.html
  copy: src=index.html dest=/var/www/html/index.html
